version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: tasksdb
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  mariadb-data:

